import * as fs from "node:fs/promises";
import * as fsSync from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Resolves the monorepo root directory by scanning upwards for workspace root markers
 * (e.g. pnpm-workspace.yaml or turbo.json).
 */
export function resolveRepoRoot(startDir?: string): string {
  try {
    let currentDir = startDir;
    if (!currentDir) {
      if (typeof import.meta !== "undefined" && import.meta?.url) {
        currentDir = path.dirname(fileURLToPath(import.meta.url));
      } else {
        currentDir = process.cwd();
      }
    }
    while (currentDir !== path.parse(currentDir).root) {
      if (
        fsSync.existsSync(path.join(currentDir, "pnpm-workspace.yaml")) ||
        fsSync.existsSync(path.join(currentDir, "turbo.json"))
      ) {
        return currentDir;
      }
      currentDir = path.dirname(currentDir);
    }
  } catch {
    // Ignore error and fall through to process.cwd() search
  }

  let cwd = process.cwd();
  while (cwd !== path.parse(cwd).root) {
    if (
      fsSync.existsSync(path.join(cwd, "pnpm-workspace.yaml")) ||
      fsSync.existsSync(path.join(cwd, "turbo.json"))
    ) {
      return cwd;
    }
    cwd = path.dirname(cwd);
  }

  return process.cwd();
}

/**
 * Alias for resolveRepoRoot for backwards compatibility with Docker/Local providers.
 */
export const findRepoRoot = resolveRepoRoot;

/**
 * Synchronously parses a .env file into key-value pairs, stripping comments and outer quotes.
 * Normalizes both Unix (\n) and Windows (\r\n) line endings.
 */
export function parseEnvFile(filePath: string): Record<string, string> {
  if (!fsSync.existsSync(filePath)) return {};
  try {
    const content = fsSync.readFileSync(filePath, "utf-8");
    const result: Record<string, string> = {};
    for (const rawLine of content.split(/\r?\n/)) {
      const line = rawLine.trim();
      if (!line || line.startsWith("#")) continue;
      const eqIdx = line.indexOf("=");
      if (eqIdx === -1) continue;
      const key = line.slice(0, eqIdx).trim();
      let value = line.slice(eqIdx + 1).trim();
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }
      result[key] = value;
    }
    return result;
  } catch {
    return {};
  }
}

/**
 * Asynchronously reads and parses an existing .env file.
 */
export async function readExistingEnv(
  filePath: string,
): Promise<Record<string, string>> {
  try {
    const content = await fs.readFile(filePath, "utf-8");
    const result: Record<string, string> = {};
    for (const rawLine of content.split(/\r?\n/)) {
      const line = rawLine.trim();
      if (!line || line.startsWith("#")) continue;
      const eqIdx = line.indexOf("=");
      if (eqIdx === -1) continue;
      const key = line.slice(0, eqIdx).trim();
      let value = line.slice(eqIdx + 1).trim();
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }
      result[key] = value;
    }
    return result;
  } catch {
    return {};
  }
}

export interface WriteEnvFileOptions {
  readonly header?: string;
  readonly mergeExisting?: boolean;
}

/**
 * Writes key-value environment variables to a .env file, creating parent directories if needed.
 * Optionally merges with existing .env variables if mergeExisting is true.
 */
export async function writeEnvFile(
  filePath: string,
  vars: Readonly<Record<string, string>>,
  options: WriteEnvFileOptions = {},
): Promise<void> {
  const merged = options.mergeExisting
    ? { ...(await readExistingEnv(filePath)), ...vars }
    : vars;

  const header = options.header
    ? [options.header, ""]
    : [
        "# Generated by VeoLMS Fleet Setup",
        "# Run pnpm fleet:infra to regenerate",
        "",
      ];

  const lines = [
    ...header,
    ...Object.entries(merged).map(([k, v]) => `${k}="${v}"`),
    "",
  ];

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, lines.join("\n"), "utf-8");
}
