export {
  AVATAR_CONTENT_TYPES,
  AVATAR_IMAGE_WIDTHS,
  AVATAR_UPLOAD_MAX_BYTES,
  avatarCdnUrl,
  avatarOriginalKey,
  avatarSrcSetFromUrl,
  detectImageContentType,
  isStoredAvatarUrl,
  removeAvatarVariants,
  removeOtherAvatarOriginals,
  removeAvatar,
  storeAvatarBuffer,
  storeAvatarFromUrl,
} from "./avatar-storage.ts";
