export type OrderHistoryStatus =
  | "completed"
  | "processing"
  | "refunded"
  | "failed"
  | "canceled";

export interface OrderHistoryPayment {
  type: "visa" | "mastercard" | "upi" | "paypal";
  label: string; // e.g. "•••• 4242", "ashisingh@upi", "ashisingh@example.com"
  brand: string; // e.g. "Visa", "Mastercard", "UPI", "PayPal"
}

export interface OrderHistoryItem {
  id: string;
  orderNumber: string; // e.g. "#ORD-240524-1001"
  invoiceNumber: string; // e.g. "INV-1001"
  courseId: string;
  courseTitle: string;
  itemCount: string; // e.g. "1 Course"
  iconColor: string; // e.g. "#3b82f6"
  date: string; // e.g. "May 24, 2025"
  time: string; // e.g. "10:30 AM"
  payment: OrderHistoryPayment;
  amount: number; // in USD
  formattedAmount: string; // e.g. "$49.00"
  status: OrderHistoryStatus;
  statusLabel: string;
  subtotal: number;
  tax: number;
  transactionId: string;
}

export type OrderHistoryTabId =
  | "all"
  | "completed"
  | "processing"
  | "refunded"
  | "failed"
  | "canceled";

export const initialOrderHistoryList: readonly OrderHistoryItem[] = [
  // Page 1
  {
    id: "ord-hist-1",
    orderNumber: "#ORD-240524-1001",
    invoiceNumber: "INV-1001",
    courseId: "typescript-course",
    courseTitle: "The Ultimate TypeScript Course",
    itemCount: "1 Course",
    iconColor: "#3b82f6", // Blue
    date: "May 24, 2025",
    time: "10:30 AM",
    payment: {
      type: "visa",
      brand: "Visa",
      label: "•••• 4242",
    },
    amount: 49.0,
    formattedAmount: "$49.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 41.53,
    tax: 7.47,
    transactionId: "TXN_VISA_9845729104",
  },
  {
    id: "ord-hist-2",
    orderNumber: "#ORD-240523-0987",
    invoiceNumber: "INV-0987",
    courseId: "backend-nodejs",
    courseTitle: "Complete Backend with Node.js",
    itemCount: "1 Course",
    iconColor: "#f59e0b", // Amber/Orange
    date: "May 23, 2025",
    time: "09:15 AM",
    payment: {
      type: "mastercard",
      brand: "Mastercard",
      label: "•••• 1234",
    },
    amount: 59.0,
    formattedAmount: "$59.00",
    status: "processing",
    statusLabel: "Processing",
    subtotal: 50.0,
    tax: 9.0,
    transactionId: "TXN_MC_7836109482",
  },
  {
    id: "ord-hist-3",
    orderNumber: "#ORD-240522-0966",
    invoiceNumber: "INV-0966",
    courseId: "python-data-science",
    courseTitle: "Python for Data Science",
    itemCount: "1 Course",
    iconColor: "#10b981", // Green
    date: "May 22, 2025",
    time: "04:45 PM",
    payment: {
      type: "upi",
      brand: "UPI",
      label: "ashisingh@upi",
    },
    amount: 39.0,
    formattedAmount: "$39.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 33.05,
    tax: 5.95,
    transactionId: "UPI_5628103947",
  },
  {
    id: "ord-hist-4",
    orderNumber: "#ORD-240521-0923",
    invoiceNumber: "INV-0923",
    courseId: "react-complete-guide",
    courseTitle: "React.js - The Complete Guide",
    itemCount: "1 Course",
    iconColor: "#8b5cf6", // Purple
    date: "May 21, 2025",
    time: "11:20 AM",
    payment: {
      type: "visa",
      brand: "Visa",
      label: "•••• 4242",
    },
    amount: 49.0,
    formattedAmount: "$49.00",
    status: "failed",
    statusLabel: "Failed",
    subtotal: 41.53,
    tax: 7.47,
    transactionId: "TXN_VISA_3920194857",
  },
  {
    id: "ord-hist-5",
    orderNumber: "#ORD-240520-0891",
    invoiceNumber: "INV-0891",
    courseId: "ui-ux-design-fundamentals",
    courseTitle: "UI/UX Design Fundamentals",
    itemCount: "1 Course",
    iconColor: "#ef4444", // Red
    date: "May 20, 2025",
    time: "02:10 PM",
    payment: {
      type: "paypal",
      brand: "PayPal",
      label: "ashisingh@example.com",
    },
    amount: 29.0,
    formattedAmount: "$29.00",
    status: "refunded",
    statusLabel: "Refunded",
    subtotal: 24.58,
    tax: 4.42,
    transactionId: "PAYPAL_6104829375",
  },
  {
    id: "ord-hist-6",
    orderNumber: "#ORD-240519-0860",
    invoiceNumber: "INV-0860",
    courseId: "javascript-zero-to-hero",
    courseTitle: "JavaScript: From Zero to Hero",
    itemCount: "1 Course",
    iconColor: "#f97316", // Orange
    date: "May 19, 2025",
    time: "08:00 AM",
    payment: {
      type: "mastercard",
      brand: "Mastercard",
      label: "•••• 1234",
    },
    amount: 49.0,
    formattedAmount: "$49.00",
    status: "canceled",
    statusLabel: "Canceled",
    subtotal: 41.53,
    tax: 7.47,
    transactionId: "TXN_MC_1948205938",
  },

  // Page 2
  {
    id: "ord-hist-7",
    orderNumber: "#ORD-240518-0842",
    invoiceNumber: "INV-0842",
    courseId: "docker-kubernetes",
    courseTitle: "Docker & Kubernetes for Developers",
    itemCount: "1 Course",
    iconColor: "#0284c7",
    date: "May 18, 2025",
    time: "03:30 PM",
    payment: { type: "visa", brand: "Visa", label: "•••• 4242" },
    amount: 59.0,
    formattedAmount: "$59.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 50.0,
    tax: 9.0,
    transactionId: "TXN_VISA_7284910293",
  },
  {
    id: "ord-hist-8",
    orderNumber: "#ORD-240517-0819",
    invoiceNumber: "INV-0819",
    courseId: "nextjs-masterclass",
    courseTitle: "Next.js Fullstack Masterclass",
    itemCount: "1 Course",
    iconColor: "#10b981",
    date: "May 17, 2025",
    time: "11:00 AM",
    payment: { type: "upi", brand: "UPI", label: "ashisingh@upi" },
    amount: 69.0,
    formattedAmount: "$69.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 58.47,
    tax: 10.53,
    transactionId: "UPI_9182736450",
  },
  {
    id: "ord-hist-9",
    orderNumber: "#ORD-240516-0795",
    invoiceNumber: "INV-0795",
    courseId: "advanced-css-animations",
    courseTitle: "Advanced CSS & Modern Animations",
    itemCount: "1 Course",
    iconColor: "#ec4899",
    date: "May 16, 2025",
    time: "01:25 PM",
    payment: { type: "paypal", brand: "PayPal", label: "ashisingh@example.com" },
    amount: 34.0,
    formattedAmount: "$34.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 28.81,
    tax: 5.19,
    transactionId: "PAYPAL_2948172039",
  },
  {
    id: "ord-hist-10",
    orderNumber: "#ORD-240515-0774",
    invoiceNumber: "INV-0774",
    courseId: "aws-cloud-architect",
    courseTitle: "AWS Certified Solutions Architect",
    itemCount: "1 Course",
    iconColor: "#f59e0b",
    date: "May 15, 2025",
    time: "05:15 PM",
    payment: { type: "mastercard", brand: "Mastercard", label: "•••• 1234" },
    amount: 79.0,
    formattedAmount: "$79.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 66.95,
    tax: 12.05,
    transactionId: "TXN_MC_8492019482",
  },
  {
    id: "ord-hist-11",
    orderNumber: "#ORD-240514-0750",
    invoiceNumber: "INV-0750",
    courseId: "graphql-api-masterclass",
    courseTitle: "GraphQL API Masterclass",
    itemCount: "1 Course",
    iconColor: "#8b5cf6",
    date: "May 14, 2025",
    time: "10:45 AM",
    payment: { type: "visa", brand: "Visa", label: "•••• 4242" },
    amount: 49.0,
    formattedAmount: "$49.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 41.53,
    tax: 7.47,
    transactionId: "TXN_VISA_1029384756",
  },
  {
    id: "ord-hist-12",
    orderNumber: "#ORD-240513-0728",
    invoiceNumber: "INV-0728",
    courseId: "postgresql-mastery",
    courseTitle: "PostgreSQL Mastery",
    itemCount: "1 Course",
    iconColor: "#3b82f6",
    date: "May 13, 2025",
    time: "02:00 PM",
    payment: { type: "upi", brand: "UPI", label: "ashisingh@upi" },
    amount: 39.0,
    formattedAmount: "$39.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 33.05,
    tax: 5.95,
    transactionId: "UPI_4920192847",
  },

  // Page 3
  {
    id: "ord-hist-13",
    orderNumber: "#ORD-240512-0701",
    invoiceNumber: "INV-0701",
    courseId: "flutter-cross-platform",
    courseTitle: "Flutter & Dart Cross-Platform Mobile",
    itemCount: "1 Course",
    iconColor: "#0284c7",
    date: "May 12, 2025",
    time: "09:30 AM",
    payment: { type: "visa", brand: "Visa", label: "•••• 4242" },
    amount: 54.0,
    formattedAmount: "$54.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 45.76,
    tax: 8.24,
    transactionId: "TXN_VISA_5829103948",
  },
  {
    id: "ord-hist-14",
    orderNumber: "#ORD-240511-0682",
    invoiceNumber: "INV-0682",
    courseId: "system-design-interview",
    courseTitle: "System Design for Large Scale Systems",
    itemCount: "1 Course",
    iconColor: "#10b981",
    date: "May 11, 2025",
    time: "04:10 PM",
    payment: { type: "mastercard", brand: "Mastercard", label: "•••• 1234" },
    amount: 69.0,
    formattedAmount: "$69.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 58.47,
    tax: 10.53,
    transactionId: "TXN_MC_3948201938",
  },
  {
    id: "ord-hist-15",
    orderNumber: "#ORD-240510-0659",
    invoiceNumber: "INV-0659",
    courseId: "rust-programming",
    courseTitle: "Rust Programming: Zero to Production",
    itemCount: "1 Course",
    iconColor: "#f97316",
    date: "May 10, 2025",
    time: "11:50 AM",
    payment: { type: "upi", brand: "UPI", label: "ashisingh@upi" },
    amount: 49.0,
    formattedAmount: "$49.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 41.53,
    tax: 7.47,
    transactionId: "UPI_2948102938",
  },
  {
    id: "ord-hist-16",
    orderNumber: "#ORD-240509-0633",
    invoiceNumber: "INV-0633",
    courseId: "golang-microservices",
    courseTitle: "Building Microservices with Go",
    itemCount: "1 Course",
    iconColor: "#3b82f6",
    date: "May 09, 2025",
    time: "01:15 PM",
    payment: { type: "visa", brand: "Visa", label: "•••• 4242" },
    amount: 59.0,
    formattedAmount: "$59.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 50.0,
    tax: 9.0,
    transactionId: "TXN_VISA_9182736451",
  },
  {
    id: "ord-hist-17",
    orderNumber: "#ORD-240508-0610",
    invoiceNumber: "INV-0610",
    courseId: "cybersecurity-essentials",
    courseTitle: "Cybersecurity & Ethical Hacking",
    itemCount: "1 Course",
    iconColor: "#ef4444",
    date: "May 08, 2025",
    time: "05:40 PM",
    payment: { type: "paypal", brand: "PayPal", label: "ashisingh@example.com" },
    amount: 49.0,
    formattedAmount: "$49.00",
    status: "failed",
    statusLabel: "Failed",
    subtotal: 41.53,
    tax: 7.47,
    transactionId: "PAYPAL_4829103948",
  },
  {
    id: "ord-hist-18",
    orderNumber: "#ORD-240507-0589",
    invoiceNumber: "INV-0589",
    courseId: "devops-ci-cd-pipelines",
    courseTitle: "DevOps, GitOps & GitHub Actions",
    itemCount: "1 Course",
    iconColor: "#8b5cf6",
    date: "May 07, 2025",
    time: "10:00 AM",
    payment: { type: "mastercard", brand: "Mastercard", label: "•••• 1234" },
    amount: 44.0,
    formattedAmount: "$44.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 37.29,
    tax: 6.71,
    transactionId: "TXN_MC_1029384759",
  },

  // Page 4
  {
    id: "ord-hist-19",
    orderNumber: "#ORD-240506-0562",
    invoiceNumber: "INV-0562",
    courseId: "linux-command-line",
    courseTitle: "Linux Command Line & Shell Scripting",
    itemCount: "1 Course",
    iconColor: "#f59e0b",
    date: "May 06, 2025",
    time: "03:10 PM",
    payment: { type: "visa", brand: "Visa", label: "•••• 4242" },
    amount: 29.0,
    formattedAmount: "$29.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 24.58,
    tax: 4.42,
    transactionId: "TXN_VISA_4920194857",
  },
  {
    id: "ord-hist-20",
    orderNumber: "#ORD-240505-0538",
    invoiceNumber: "INV-0538",
    courseId: "redis-caching-mastery",
    courseTitle: "Redis for High Performance Caching",
    itemCount: "1 Course",
    iconColor: "#ef4444",
    date: "May 05, 2025",
    time: "08:45 AM",
    payment: { type: "upi", brand: "UPI", label: "ashisingh@upi" },
    amount: 39.0,
    formattedAmount: "$39.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 33.05,
    tax: 5.95,
    transactionId: "UPI_9182736452",
  },
  {
    id: "ord-hist-21",
    orderNumber: "#ORD-240504-0511",
    invoiceNumber: "INV-0511",
    courseId: "web3-solidity-smart-contracts",
    courseTitle: "Web3 & Solidity Smart Contracts",
    itemCount: "1 Course",
    iconColor: "#8b5cf6",
    date: "May 04, 2025",
    time: "12:15 PM",
    payment: { type: "mastercard", brand: "Mastercard", label: "•••• 1234" },
    amount: 59.0,
    formattedAmount: "$59.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 50.0,
    tax: 9.0,
    transactionId: "TXN_MC_5829103949",
  },
  {
    id: "ord-hist-22",
    orderNumber: "#ORD-240503-0487",
    invoiceNumber: "INV-0487",
    courseId: "deep-learning-pytorch",
    courseTitle: "Deep Learning with PyTorch",
    itemCount: "1 Course",
    iconColor: "#10b981",
    date: "May 03, 2025",
    time: "02:50 PM",
    payment: { type: "visa", brand: "Visa", label: "•••• 4242" },
    amount: 69.0,
    formattedAmount: "$69.00",
    status: "completed",
    statusLabel: "Completed",
    subtotal: 58.47,
    tax: 10.53,
    transactionId: "TXN_VISA_2948172040",
  },
  {
    id: "ord-hist-23",
    orderNumber: "#ORD-240502-0461",
    invoiceNumber: "INV-0461",
    courseId: "tailwind-design-systems",
    courseTitle: "Building UI Design Systems with Tailwind",
    itemCount: "1 Course",
    iconColor: "#0284c7",
    date: "May 02, 2025",
    time: "09:00 AM",
    payment: { type: "paypal", brand: "PayPal", label: "ashisingh@example.com" },
    amount: 34.0,
    formattedAmount: "$34.00",
    status: "processing",
    statusLabel: "Processing",
    subtotal: 28.81,
    tax: 5.19,
    transactionId: "PAYPAL_8492019483",
  },
  {
    id: "ord-hist-24",
    orderNumber: "#ORD-240501-0435",
    invoiceNumber: "INV-0435",
    courseId: "vue3-pinia-mastery",
    courseTitle: "Vue 3, Pinia & Vite Full Course",
    itemCount: "1 Course",
    iconColor: "#10b981",
    date: "May 01, 2025",
    time: "04:30 PM",
    payment: { type: "upi", brand: "UPI", label: "ashisingh@upi" },
    amount: 44.0,
    formattedAmount: "$44.00",
    status: "refunded",
    statusLabel: "Refunded",
    subtotal: 37.29,
    tax: 6.71,
    transactionId: "UPI_1029384760",
  },
];

export const orderHistoryTabCounts = {
  all: 24,
  completed: 18,
  processing: 2,
  refunded: 2,
  failed: 2,
  canceled: 0,
};
