/**
 * VeoLMS Docker Provider Infrastructure Setup
 *
 * Configures environment files and provisions local Docker infrastructure:
 *  - Verifies Docker CLI & engine availability
 *  - Creates Docker bridge network (veolms-fleet)
 *  - Prepares host-mounted s3-bucket directories (raw and output)
 *  - Verifies worker container image availability
 *  - Writes per-app .env files for apps/fleet-manager and apps/media-worker
 *
 * Dispatched via: apps/fleet-manager/src/cli.ts's "infra" command
 * Triggered by:   pnpm fleet:infra  (when FLEET_PROVIDER=docker)
 */

import { execSync } from "node:child_process";
import * as fs from "node:fs/promises";
import * as fsSync from "node:fs";
import * as path from "node:path";
import { stdin as input, stdout as output } from "node:process";
import * as readline from "node:readline/promises";
import { fileURLToPath } from "node:url";
import type {
  ProviderConfigOptions,
  ProviderConfigResult,
  ProviderInfraOptions,
  ProviderInfraResult,
} from "@veolms/fleet-types";
import {
  ask,
  askChoice,
  bold,
  cyan,
  dim,
  execCommand as checkCommand,
  fail,
  green,
  isNonInteractive,
  isReadlineInterface,
  ok,
  red,
  warn,
  yellow,
} from "@veolms/fleet-types/terminal";

import {
  readExistingEnv,
  resolveRepoRoot as findRepoRoot,
  writeEnvFile as baseWriteEnvFile,
} from "@veolms/fleet-types/env";
import { isMainModule } from "@veolms/fleet-types";

export { isReadlineInterface };

function detectDockerSocketGid(): string | undefined {
  if (process.platform === "win32") {
    return "0";
  }
  try {
    const operatingSystem = execSync(
      'docker info --format "{{.OperatingSystem}}"',
      {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      },
    ).trim();
    if (/docker desktop/i.test(operatingSystem)) {
      return "0";
    }
  } catch {
    // Fall back to the host socket metadata when Docker info is unavailable.
  }

  try {
    const gid = execSync("stat -c %g /var/run/docker.sock", {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    return /^\d+$/.test(gid) ? gid : undefined;
  } catch {
    return undefined;
  }
}

async function writeEnvFile(
  filePath: string,
  vars: Readonly<Record<string, string>>,
): Promise<void> {
  await baseWriteEnvFile(filePath, vars, {
    header:
      "# Generated by VeoLMS Docker Infrastructure Setup\n# Run: pnpm fleet:infra --provider=docker  to regenerate",
    mergeExisting: true,
  });
  ok(`Written ${bold(path.relative(process.cwd(), filePath))}`);
}

/**
 * Configures the environment and generates .env files for the Docker provider.
 */
export async function configureEnv(
  options: ProviderConfigOptions & { rl?: readline.Interface } = {},
): Promise<ProviderConfigResult> {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const repoRoot = findRepoRoot(__dirname);
  const nonInteractive = isNonInteractive(options);
  const shouldCloseRl =
    !isReadlineInterface(options.rl) && !nonInteractive && process.stdin.isTTY;
  const rl: readline.Interface | undefined = isReadlineInterface(options.rl)
    ? options.rl
    : shouldCloseRl
      ? readline.createInterface({ input, output })
      : undefined;

  try {
    console.log(`
${bold(cyan("╔══════════════════════════════════════════════════════════╗"))}
${bold(cyan("║"))}        ${bold("VeoLMS Docker Provider Setup")}                ${bold(cyan("║"))}
${bold(cyan("║"))}     Prepares environment & local Docker infrastructure ${bold(cyan("║"))}
${bold(cyan("╚══════════════════════════════════════════════════════════╝"))}
`);

    console.log(`\n${bold(cyan("[1/3]"))} ${bold("Checking Docker Engine")}`);
    console.log(dim("─".repeat(52)));

    const dockerVersion = checkCommand("docker --version");
    if (!dockerVersion) {
      fail("Docker CLI not found.");
      console.error(`
  ${bold("Install Docker Engine:")}
    ${cyan("https://docs.docker.com/engine/install/")}
`);
      throw new Error("Docker CLI is required but not installed.");
    }
    ok(`Docker CLI found — ${bold(dockerVersion)}`);

    const dockerInfo = checkCommand(
      'docker info --format "{{.ServerVersion}}"',
    );
    if (!dockerInfo) {
      warn(
        "Docker daemon does not appear to be running or current user lacks socket permissions.",
      );
    } else {
      ok(`Docker daemon is active — version ${bold(dockerInfo)}`);
    }

    const socketGid = detectDockerSocketGid();
    if (socketGid) {
      ok(`Detected Docker socket GID: ${bold(socketGid)}`);
    }

    console.log(`\n${bold(cyan("[2/3]"))} ${bold("Preparing Storage Paths")}`);
    console.log(dim("─".repeat(52)));

    const s3BucketDir = path.join(repoRoot, "s3-bucket");
    await fs.mkdir(path.join(s3BucketDir, "raw"), { recursive: true });
    await fs.mkdir(path.join(s3BucketDir, "output"), { recursive: true });
    ok(
      `Storage root verified at ${bold(path.relative(process.cwd(), s3BucketDir))}`,
    );

    console.log(
      `\n${bold(cyan("[3/3]"))} ${bold("Configuring Environment (.env)")}`,
    );
    console.log(dim("─".repeat(52)));

    const fleetEnvPath = path.join(repoRoot, "apps", "fleet-manager", ".env");
    const workerEnvPath = path.join(repoRoot, "apps", "media-worker", ".env");

    const rootEnv = await readExistingEnv(path.join(repoRoot, ".env"));
    const existingFleetEnv = await readExistingEnv(fleetEnvPath);
    const existingWorkerEnv = await readExistingEnv(workerEnvPath);

    // ── Part 1: Core Fleet Configuration (Common across Providers) ──────────
    console.log(`\n${bold(cyan("── Part 1: Core Fleet Configuration ──"))}`);

    const defaultDatabaseUrl =
      process.env.DATABASE_URL ||
      existingFleetEnv["DATABASE_URL"] ||
      existingWorkerEnv["DATABASE_URL"] ||
      rootEnv["DATABASE_URL"] ||
      "postgresql://veolms:veolms@localhost:5433/veolms";

    const databaseUrl = await ask(
      rl,
      "PostgreSQL DATABASE_URL (for worker status & job claims)",
      defaultDatabaseUrl,
      nonInteractive,
    );

    const defaultMaxWorkers =
      process.env.MAX_WORKERS || existingFleetEnv["MAX_WORKERS"] || "8";
    const maxWorkers = await ask(
      rl,
      "Maximum concurrent worker containers (MAX_WORKERS)",
      defaultMaxWorkers,
      nonInteractive,
    );

    const defaultIdlePollSec =
      process.env.WORKER_IDLE_POLL_SECONDS ||
      existingWorkerEnv["WORKER_IDLE_POLL_SECONDS"] ||
      "15";
    const idlePollSec = await ask(
      rl,
      "Worker idle poll timeout in seconds (WORKER_IDLE_POLL_SECONDS)",
      defaultIdlePollSec,
      nonInteractive,
    );

    // ── Part 2: Docker Provider Configuration (Docker Specific) ─────────────
    console.log(
      `\n${bold(cyan("── Part 2: Docker Provider Configuration ──"))}`,
    );

    const defaultWorkerImage =
      process.env.DOCKER_WORKER_IMAGE ||
      existingFleetEnv["DOCKER_WORKER_IMAGE"] ||
      "veolms-media-worker:local";
    const workerImage = await ask(
      rl,
      "Worker container image (DOCKER_WORKER_IMAGE)",
      defaultWorkerImage,
      nonInteractive,
    );

    const defaultNetwork =
      process.env.DOCKER_NETWORK ||
      existingFleetEnv["DOCKER_NETWORK"] ||
      "veolms-fleet";
    const dockerNetwork = await ask(
      rl,
      "Docker bridge network (DOCKER_NETWORK)",
      defaultNetwork,
      nonInteractive,
    );

    const defaultStorageRoot =
      process.env.DOCKER_STORAGE_ROOT ||
      existingFleetEnv["DOCKER_STORAGE_ROOT"] ||
      s3BucketDir;
    const localStorageRoot = await ask(
      rl,
      "Host storage root directory (LOCAL_STORAGE_ROOT)",
      defaultStorageRoot,
      nonInteractive,
    );

    const defaultTransport =
      (process.env.DOCKER_TRANSPORT as "cli" | "socket") ||
      (existingFleetEnv["DOCKER_TRANSPORT"] as "cli" | "socket") ||
      "cli";
    const transportChoices = [
      {
        label: "Docker CLI (Standard host Docker execution)",
        value: "cli" as const,
      },
      {
        label:
          "Docker Engine Unix Socket (Required inside container/LocalStack)",
        value: "socket" as const,
      },
    ];
    const defaultTransportIdx = defaultTransport === "socket" ? 1 : 0;
    const dockerTransport = await askChoice(
      rl,
      "Docker engine transport mechanism (DOCKER_TRANSPORT)",
      transportChoices,
      defaultTransportIdx,
      nonInteractive,
    );

    const fleetEnv: Record<string, string> = {
      FLEET_PROVIDER: "docker",
      PROVIDER: "docker",
      FLEET_MODE: "serverful",
      STORAGE_PROVIDER: "local",
      DOCKER_WORKER_IMAGE: workerImage,
      DOCKER_NETWORK: dockerNetwork,
      DOCKER_TRANSPORT: dockerTransport,
      DOCKER_SOCKET_PATH: "/var/run/docker.sock",
      DOCKER_STORAGE_ROOT: localStorageRoot,
      DOCKER_VERIFICATION_STORAGE_ROOT: "/app/s3-bucket",
      LOCAL_STORAGE_ROOT: "/app/s3-bucket",
      DATABASE_URL: databaseUrl,
      MAX_WORKERS: maxWorkers,
      FLEET_TEST_MODE: "true",
      ...(socketGid ? { DOCKER_SOCKET_GID: socketGid } : {}),
    };

    const workerEnv: Record<string, string> = {
      FLEET_PROVIDER: "docker",
      STORAGE_PROVIDER: "local",
      LOCAL_STORAGE_ROOT: "/app/s3-bucket",
      DATABASE_URL: databaseUrl,
      WORKER_IDLE_POLL_SECONDS: idlePollSec,
    };

    await writeEnvFile(fleetEnvPath, fleetEnv);
    await writeEnvFile(workerEnvPath, workerEnv);

    return {
      provider: "docker",
      envFiles: [fleetEnvPath, workerEnvPath],
      config: {
        databaseUrl,
        workerImage,
        dockerNetwork,
        localStorageRoot,
        dockerTransport,
      },
    };
  } finally {
    if (shouldCloseRl && rl) {
      rl.close();
    }
  }
}

/**
 * Provisions Docker infrastructure (networks, storage directories, database migrations, and image building/updating).
 */
export async function provisionInfra(
  options: ProviderInfraOptions & { rl?: readline.Interface } = {},
): Promise<ProviderInfraResult> {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const repoRoot = findRepoRoot(__dirname);
  const createdResources: string[] = [];
  const isUpdate = Boolean(options.update);
  const nonInteractive = isNonInteractive(options);

  // 1. Storage directories
  console.log(
    `\n${bold(cyan("[1/3]"))} ${bold("Preparing Host Storage Directories")}`,
  );
  console.log(dim("─".repeat(52)));
  const s3BucketDir = path.join(repoRoot, "s3-bucket");
  await fs.mkdir(path.join(s3BucketDir, "raw"), { recursive: true });
  await fs.mkdir(path.join(s3BucketDir, "output"), { recursive: true });
  createdResources.push("s3-bucket/raw", "s3-bucket/output");
  ok(
    `Host storage mount verified at ${bold(path.relative(process.cwd(), s3BucketDir))}`,
  );

  // 2. Docker Network
  console.log(
    `\n${bold(cyan("[2/3]"))} ${bold("Configuring Docker Bridge Network")}`,
  );
  console.log(dim("─".repeat(52)));
  const networkName = "veolms-fleet";
  const networkExists = checkCommand(`docker network inspect ${networkName}`);
  if (!networkExists) {
    const createResult = checkCommand(`docker network create ${networkName}`);
    if (createResult) {
      ok(`Created Docker bridge network: ${bold(networkName)}`);
      createdResources.push(`docker-network:${networkName}`);
    } else {
      warn(
        `Could not create network ${networkName}; continuing with default bridge.`,
      );
    }
  } else {
    ok(`Docker bridge network ${bold(networkName)} is ready.`);
  }

  // 3. Docker Container Image Building / Updating
  console.log(
    `\n${bold(cyan("[3/3]"))} ${bold(isUpdate ? "Updating Docker Container Images" : "Building Docker Container Images")}`,
  );
  console.log(dim("─".repeat(52)));
  const pnpmCmd = process.platform === "win32" ? "pnpm.cmd" : "pnpm";
  const workerImage = "veolms-media-worker:local";
  const managerImage = "veolms-fleet-manager:local";

  const workerImageExists = Boolean(
    checkCommand(`docker image inspect ${workerImage}`),
  );
  const managerImageExists = Boolean(
    checkCommand(`docker image inspect ${managerImage}`),
  );

  let buildImages = isUpdate || !workerImageExists || !managerImageExists;

  if (
    !isUpdate &&
    workerImageExists &&
    managerImageExists &&
    !nonInteractive &&
    options.rl
  ) {
    const choices = [
      {
        label: "Keep existing Docker images (skip rebuild)",
        value: "keep" as const,
      },
      {
        label: "Rebuild and update Docker images now",
        value: "rebuild" as const,
      },
    ];
    const rebuildChoice = await askChoice(
      options.rl,
      "Docker worker and manager images already exist. Rebuild now?",
      choices,
      0,
      false,
    );
    buildImages = rebuildChoice === "rebuild";
  }

  if (buildImages) {
    console.log(
      `\n  Building worker bundle & container image (${bold(workerImage)})...`,
    );
    execSync(`${pnpmCmd} --filter @veolms/media-worker build:bundle`, {
      cwd: repoRoot,
      stdio: "inherit",
    });
    execSync(`docker build -t ${workerImage} apps/media-worker`, {
      cwd: repoRoot,
      stdio: "inherit",
    });
    ok(`Worker container image ${bold(workerImage)} built successfully.`);
    createdResources.push(`docker-image:${workerImage}`);

    console.log(
      `\n  Building fleet-manager bundle & container image (${bold(managerImage)})...`,
    );
    execSync(`${pnpmCmd} --filter @veolms/fleet-manager build:bundle`, {
      cwd: repoRoot,
      stdio: "inherit",
    });
    execSync(`docker build -t ${managerImage} apps/fleet-manager`, {
      cwd: repoRoot,
      stdio: "inherit",
    });
    ok(
      `Fleet manager container image ${bold(managerImage)} built successfully.`,
    );
    createdResources.push(`docker-image:${managerImage}`);
  } else {
    ok(
      `Docker images (${bold(workerImage)}, ${bold(managerImage)}) are present and up to date.`,
    );
  }

  // 4. Start Fleet Manager Container
  console.log(
    `\n${bold(cyan("[4/4]"))} ${bold("Starting Fleet Manager Container")}`,
  );
  console.log(dim("─".repeat(52)));

  let startContainer =
    typeof options["start"] === "boolean" ? options["start"] : undefined;
  if (startContainer === undefined && !nonInteractive && options.rl) {
    const choices = [
      {
        label:
          "Yes, start Fleet Manager container now (runs in background via Docker Compose)",
        value: "yes" as const,
      },
      {
        label:
          "No, keep stopped (I will start it manually or run in-process with pnpm fleet:cli run daemon)",
        value: "no" as const,
      },
    ];
    const startChoice = await askChoice(
      options.rl,
      "Do you want to start the Fleet Manager container now?",
      choices,
      0,
      false,
    );
    startContainer = startChoice === "yes";
  }

  let containerStarted = false;
  if (startContainer) {
    console.log(`\n  Starting Fleet Manager daemon container in background...`);
    try {
      execSync(
        `docker compose --env-file apps/fleet-manager/.env -f compose.fleet.yaml --profile serverful up -d`,
        { cwd: repoRoot, stdio: "inherit" },
      );
      ok("Fleet Manager container started in background.");
      createdResources.push("docker-container:fleet-manager");
      containerStarted = true;
    } catch (startErr: unknown) {
      warn(`Could not start Fleet Manager container: ${String(startErr)}`);
    }
  }

  console.log(`
${bold(cyan("╔══════════════════════════════════════════════════════════╗"))}
${bold(cyan("║"))}            ${bold(green(isUpdate ? "Docker Update Complete!" : "Docker Setup Complete!"))}                ${bold(cyan("║"))}
${bold(cyan("╚══════════════════════════════════════════════════════════╝"))}

${bold("Configuration:")}
  ${green("✔")} apps/fleet-manager/.env
  ${green("✔")} apps/media-worker/.env
  ${green("✔")} Docker images ready (${workerImage}, ${managerImage})
${containerStarted ? `  ${green("✔")} Fleet Manager container running in background\n` : ""}
${bold("Next Steps:")}
${
  containerStarted
    ? `  1. Queue & trigger transcoding:  ${cyan("pnpm fleet:queue:trigger")}
  2. Monitor fleet status:         ${cyan("pnpm fleet:cli status")}
  3. List active workers:          ${cyan("pnpm fleet:cli workers")}
  4. Teardown or stop:             ${cyan("pnpm fleet:destroy")}`
    : `  1. Run Fleet Manager:
     - In-process CLI runner:      ${cyan("pnpm fleet:cli run daemon")}
     - Or containerized daemon:    ${cyan("docker compose --env-file apps/fleet-manager/.env -f compose.fleet.yaml --profile serverful up -d")}

  2. Queue & trigger transcoding:  ${cyan("pnpm fleet:queue:trigger")}
  3. Monitor fleet status:         ${cyan("pnpm fleet:cli status")}
  4. Teardown or stop:             ${cyan("pnpm fleet:destroy")}`
}
`);

  return {
    success: true,
    provider: "docker",
    details: {
      createdResources,
      updated: isUpdate,
      containerStarted,
    },
  };
}

/**
 * Full infrastructure setup workflow:
 * 1. Checks if running as an update (--update) or fresh setup
 * 2. Runs configureEnv() if needed
 * 3. Prompts user confirmation
 * 4. Runs provisionInfra() (storage, network, container image builds)
 */
export async function runInfraSetup(
  options: ProviderInfraOptions = {},
): Promise<void> {
  const nonInteractive = isNonInteractive(options);
  let rl: readline.Interface | undefined;
  if (!nonInteractive && process.stdin.isTTY) {
    rl = readline.createInterface({ input, output });
  }

  try {
    const __dirname = path.dirname(fileURLToPath(import.meta.url));
    const repoRoot = findRepoRoot(__dirname);
    const fleetEnvPath = path.join(repoRoot, "apps", "fleet-manager", ".env");
    const envExists = fsSync.existsSync(fleetEnvPath);

    // If --update is specified and .env already exists, skip re-asking env configuration
    if (options.update && envExists) {
      console.log(`
${bold(cyan("╔══════════════════════════════════════════════════════════╗"))}
${bold(cyan("║"))}        ${bold("VeoLMS Docker Provider Update")}               ${bold(cyan("║"))}
${bold(cyan("║"))}         Rebuilding container images                ${bold(cyan("║"))}
${bold(cyan("╚══════════════════════════════════════════════════════════╝"))}
`);
      await provisionInfra({ ...options, rl, update: true });
      return;
    }

    if (!options.skipEnvConfig) {
      const configResult = await configureEnv({
        ...options,
        rl,
      });

      if (rl) {
        console.log(`
${bold(cyan("--------------------------------------------------"))}
${bold(green("✔ Configuration saved!"))}
Please check envs on the paths:
${configResult.envFiles.map((f) => `  ${cyan("• " + path.relative(process.cwd(), f))}`).join("\n")}
You can change them if needed.
`);
        const answer = (
          await rl.question(
            bold(
              yellow(
                "Proceed with infrastructure provisioning and container builds? (yes/no) [yes]: ",
              ),
            ),
          )
        )
          .trim()
          .toLowerCase();

        if (answer && answer !== "yes" && answer !== "y") {
          console.log(yellow("Infrastructure provisioning cancelled by user."));
          return;
        }
      }
    }

    await provisionInfra({ ...options, rl });
  } finally {
    if (rl) {
      rl.close();
    }
  }
}

export const runDockerInfraSetup = runInfraSetup;
export default runInfraSetup;

if (isMainModule(import.meta.url)) {
  runInfraSetup().catch((err: unknown) => {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`\n✘ Setup failed: ${msg}\n`);
    process.exit(1);
  });
}
