export const LEARNING_PLAYER_MINIMIZE_SHORTCUT = "I";
export const LEARNING_PLAYER_MINIMIZE_LABEL = "Minimize";
export const LEARNING_PLAYER_MINIMIZE_TITLE = `${LEARNING_PLAYER_MINIMIZE_LABEL} (${LEARNING_PLAYER_MINIMIZE_SHORTCUT})`;
export const LEARNING_PLAYER_EXPAND_LABEL = "Expand";
export const LEARNING_PLAYER_EXPAND_TITLE = `${LEARNING_PLAYER_EXPAND_LABEL} (${LEARNING_PLAYER_MINIMIZE_SHORTCUT})`;
