/**
 * VeoLMS Local Provider Infrastructure Setup
 *
 * For the local provider there is no cloud infrastructure to provision.
 * This setup verifies that the local machine has the required tools
 * installed: Node.js 24+ and FFmpeg.
 *
 * Dispatched via: apps/fleet-manager/src/cli.ts's "infra" command
 * Triggered by:   pnpm fleet:infra  (when FLEET_PROVIDER=local)
 */

import { execSync } from "node:child_process";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import {
  bold,
  cyan,
  dim,
  green,
  red,
  yellow,
} from "@veolms/fleet-types/terminal";

function ok(msg: string): void {
  console.log(`  ${green("✔")} ${msg}`);
}
function warn(msg: string): void {
  console.log(`  ${yellow("⚠")} ${msg}`);
}
function fail(msg: string): void {
  console.log(`  ${red("✘")} ${msg}`);
}

function checkCommand(cmd: string): string | null {
  try {
    return execSync(`${cmd} 2>&1`, { encoding: "utf-8" }).trim();
  } catch {
    return null;
  }
}

async function writeEnvFile(
  filePath: string,
  vars: Readonly<Record<string, string>>,
): Promise<void> {
  const lines = [
    "# Generated by VeoLMS Local Infrastructure Setup",
    `# Run: pnpm fleet:infra  to regenerate`,
    "",
    ...Object.entries(vars).map(([k, v]) => `${k}="${v}"`),
    "",
  ];
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, lines.join("\n"), "utf-8");
  ok(`Written ${bold(path.relative(process.cwd(), filePath))}`);
}

/**
 * Main entry point for local infrastructure setup.
 * Called by apps/fleet-manager/src/infra.ts when FLEET_PROVIDER=local.
 */
export async function runLocalInfraSetup(): Promise<void> {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const repoRoot = path.resolve(__dirname, "..", "..", "..", "..");

  console.log(`
${bold(cyan("╔══════════════════════════════════════════════════════╗"))}
${bold(cyan("║"))}        ${bold("VeoLMS Local Provider Setup")}                 ${bold(cyan("║"))}
${bold(cyan("║"))}     Verifies local machine tool dependencies         ${bold(cyan("║"))}
${bold(cyan("╚══════════════════════════════════════════════════════╝"))}
`);

  console.log(`\n${bold(cyan("[1/3]"))} ${bold("Checking Node.js")}`);
  console.log(dim("─".repeat(52)));

  const nodeVersion = checkCommand("node --version");
  if (!nodeVersion) {
    fail("Node.js not found.");
    console.error(`
  ${bold("Install Node.js 24:")}
    ${cyan("curl -fsSL https://deb.nodesource.com/setup_24.x | bash -")}
    ${cyan("apt-get install -y nodejs")}
`);
    throw new Error("Node.js is required but not installed.");
  }

  const major = parseInt(nodeVersion.replace("v", "").split(".")[0] ?? "0", 10);
  if (major < 24) {
    warn(`Node.js ${nodeVersion} found — version 24+ is required.`);
    warn(
      `Upgrade: ${cyan("https://nodejs.org")} or use ${cyan("nvm install 24")}`,
    );
  } else {
    ok(`Node.js ${bold(nodeVersion)} — OK`);
  }

  console.log(`\n${bold(cyan("[2/3]"))} ${bold("Checking FFmpeg")}`);
  console.log(dim("─".repeat(52)));

  const ffmpegVersion = checkCommand("ffmpeg -version");
  if (!ffmpegVersion) {
    fail("FFmpeg not found.");
    console.error(`
  ${bold("Install FFmpeg:")}
    ${cyan("apt-get update && apt-get install -y ffmpeg")}   ${dim("# Debian / Ubuntu")}
    ${cyan("brew install ffmpeg")}                           ${dim("# macOS")}
`);
    throw new Error("FFmpeg is required but not installed.");
  }

  const ffmpegLine = ffmpegVersion.split("\n")[0] ?? "";
  ok(`FFmpeg found — ${bold(ffmpegLine.split(",")[0] ?? ffmpegLine)}`);

  console.log(`\n${bold(cyan("[3/3]"))} ${bold("Writing Per-App .env Files")}`);
  console.log(dim("─".repeat(52)));

  const fleetEnv: Record<string, string> = {
    FLEET_PROVIDER: "local",
    PROVIDER: "local",
    FLEET_MODE: "serverful",
    STORAGE_PROVIDER: "local",
    MAX_WORKERS: "4",
  };

  const workerEnv: Record<string, string> = {
    FLEET_PROVIDER: "local",
    STORAGE_PROVIDER: "local",
    WORKER_IDLE_POLL_SECONDS: "15",
  };

  await writeEnvFile(
    path.join(repoRoot, "apps", "fleet-manager", ".env"),
    fleetEnv,
  );
  await writeEnvFile(
    path.join(repoRoot, "apps", "media-worker", ".env"),
    workerEnv,
  );

  console.log(`
${bold(cyan("╔══════════════════════════════════════════════════════╗"))}
${bold(cyan("║"))}            ${bold(green("Local Setup Complete!"))}                ${bold(cyan("║"))}
${bold(cyan("╚══════════════════════════════════════════════════════╝"))}

${bold("Verified:")}
  ${green("✔")} Node.js ${nodeVersion ?? ""}
  ${green("✔")} FFmpeg

${bold("Generated .env Files:")}
  ${green("✔")} apps/fleet-manager/.env
  ${green("✔")} apps/media-worker/.env

${bold("Next Steps:")}
  1. Run the automated pipeline test: ${cyan("pnpm test:pipeline")}
  2. Or run the fleet daemon manually: ${cyan("pnpm fleet:run")}
  3. Monitor fleet health:            ${cyan("pnpm fleet:cli status")}
`);
}
