/**
 * VeoLMS Local Provider Infrastructure Setup
 *
 * For the local provider there is no cloud infrastructure to provision.
 * This setup verifies that the local machine has the required tools
 * installed: Node.js 24+ and FFmpeg.
 *
 * Dispatched via: apps/fleet-manager/src/cli.ts's "infra" command
 * Triggered by:   pnpm fleet:infra  (when FLEET_PROVIDER=local)
 */

import { execSync } from "node:child_process";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { stdin as input, stdout as output } from "node:process";
import * as readline from "node:readline/promises";
import { fileURLToPath } from "node:url";
import type {
  ProviderConfigOptions,
  ProviderConfigResult,
  ProviderInfraOptions,
  ProviderInfraResult,
} from "@veolms/fleet-types";
import {
  bold,
  cyan,
  dim,
  green,
  red,
  yellow,
} from "@veolms/fleet-types/terminal";
import { isMainModule } from "@veolms/fleet-types";

function ok(msg: string): void {
  console.log(`  ${green("✔")} ${msg}`);
}
function warn(msg: string): void {
  console.log(`  ${yellow("⚠")} ${msg}`);
}
function fail(msg: string): void {
  console.log(`  ${red("✘")} ${msg}`);
}

function checkCommand(cmd: string): string | null {
  try {
    return execSync(`${cmd} 2>&1`, { encoding: "utf-8" }).trim();
  } catch {
    return null;
  }
}

async function readExistingEnv(
  filePath: string,
): Promise<Record<string, string>> {
  try {
    const content = await fs.readFile(filePath, "utf-8");
    const result: Record<string, string> = {};
    for (const line of content.split(/\r?\n/)) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx !== -1) {
        const key = trimmed.slice(0, eqIdx).trim();
        let val = trimmed.slice(eqIdx + 1).trim();
        if (
          (val.startsWith('"') && val.endsWith('"')) ||
          (val.startsWith("'") && val.endsWith("'"))
        ) {
          val = val.slice(1, -1);
        }
        result[key] = val;
      }
    }
    return result;
  } catch {
    return {};
  }
}

async function writeEnvFile(
  filePath: string,
  vars: Readonly<Record<string, string>>,
): Promise<void> {
  const existing = await readExistingEnv(filePath);
  const merged = { ...existing, ...vars };
  const lines = [
    "# Generated by VeoLMS Local Infrastructure Setup",
    `# Run: pnpm fleet:infra  to regenerate`,
    "",
    ...Object.entries(merged).map(([k, v]) => `${k}="${v}"`),
    "",
  ];
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, lines.join("\n"), "utf-8");
  ok(`Written ${bold(path.relative(process.cwd(), filePath))}`);
}

/**
 * Configures the environment and generates .env files for local provider.
 */
export async function configureEnv(
  _options: ProviderConfigOptions = {},
): Promise<ProviderConfigResult> {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const repoRoot = path.resolve(__dirname, "..", "..", "..", "..");

  console.log(`
${bold(cyan("╔══════════════════════════════════════════════════════╗"))}
${bold(cyan("║"))}        ${bold("VeoLMS Local Provider Setup")}                 ${bold(cyan("║"))}
${bold(cyan("║"))}     Verifies local machine tool dependencies         ${bold(cyan("║"))}
${bold(cyan("╚══════════════════════════════════════════════════════╝"))}
`);

  console.log(`\n${bold(cyan("[1/3]"))} ${bold("Checking Node.js")}`);
  console.log(dim("─".repeat(52)));

  const nodeVersion = checkCommand("node --version");
  if (!nodeVersion) {
    fail("Node.js not found.");
    console.error(`
  ${bold("Install Node.js 24:")}
    ${cyan("curl -fsSL https://deb.nodesource.com/setup_24.x | bash -")}
    ${cyan("apt-get install -y nodejs")}
`);
    throw new Error("Node.js is required but not installed.");
  }

  const major = parseInt(nodeVersion.replace("v", "").split(".")[0] ?? "0", 10);
  if (major < 24) {
    warn(`Node.js ${nodeVersion} found — version 24+ is required.`);
    warn(
      `Upgrade: ${cyan("https://nodejs.org")} or use ${cyan("nvm install 24")}`,
    );
  } else {
    ok(`Node.js ${bold(nodeVersion)} — OK`);
  }

  console.log(`\n${bold(cyan("[2/3]"))} ${bold("Checking FFmpeg")}`);
  console.log(dim("─".repeat(52)));

  const ffmpegVersion = checkCommand("ffmpeg -version");
  if (!ffmpegVersion) {
    fail("FFmpeg not found.");
    console.error(`
  ${bold("Install FFmpeg:")}
    ${cyan("apt-get update && apt-get install -y ffmpeg")}   ${dim("# Debian / Ubuntu")}
    ${cyan("brew install ffmpeg")}                           ${dim("# macOS")}
    ${cyan("winget install Gyan.FFmpeg")}                    ${dim("# Windows")}
`);
    throw new Error("FFmpeg is required but not installed.");
  }

  const ffmpegLine = ffmpegVersion.split(/\r?\n/)[0]?.trim() ?? "";
  ok(`FFmpeg found — ${bold(ffmpegLine.split(",")[0] ?? ffmpegLine)}`);

  console.log(`\n${bold(cyan("[3/3]"))} ${bold("Writing Per-App .env Files")}`);
  console.log(dim("─".repeat(52)));

  const fleetEnvPath = path.join(repoRoot, "apps", "fleet-manager", ".env");
  const workerEnvPath = path.join(repoRoot, "apps", "media-worker", ".env");

  const rootEnv = await readExistingEnv(path.join(repoRoot, ".env"));
  const existingFleetEnv = await readExistingEnv(fleetEnvPath);
  const existingWorkerEnv = await readExistingEnv(workerEnvPath);

  const resolvedDatabaseUrl =
    process.env.DATABASE_URL ||
    existingFleetEnv["DATABASE_URL"] ||
    existingWorkerEnv["DATABASE_URL"] ||
    rootEnv["DATABASE_URL"];

  const fleetEnv: Record<string, string> = {
    FLEET_PROVIDER: "local",
    PROVIDER: "local",
    FLEET_MODE: "serverful",
    STORAGE_PROVIDER: "local",
    MAX_WORKERS: "4",
    ...(resolvedDatabaseUrl ? { DATABASE_URL: resolvedDatabaseUrl } : {}),
  };

  const workerEnv: Record<string, string> = {
    FLEET_PROVIDER: "local",
    STORAGE_PROVIDER: "local",
    WORKER_IDLE_POLL_SECONDS: "15",
    ...(resolvedDatabaseUrl ? { DATABASE_URL: resolvedDatabaseUrl } : {}),
  };

  await writeEnvFile(fleetEnvPath, fleetEnv);
  await writeEnvFile(workerEnvPath, workerEnv);

  return {
    provider: "local",
    envFiles: [fleetEnvPath, workerEnvPath],
  };
}

/**
 * Provisions local infrastructure (storage directories and verification).
 */
export async function provisionInfra(
  _options: ProviderInfraOptions = {},
): Promise<ProviderInfraResult> {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const repoRoot = path.resolve(__dirname, "..", "..", "..", "..");

  const s3BucketDir = path.join(repoRoot, "s3-bucket");
  await fs.mkdir(path.join(s3BucketDir, "raw"), { recursive: true });
  await fs.mkdir(path.join(s3BucketDir, "output"), { recursive: true });
  ok(
    `Local storage directory verified at ${bold(path.relative(process.cwd(), s3BucketDir))}`,
  );

  console.log(`
${bold(cyan("╔══════════════════════════════════════════════════════╗"))}
${bold(cyan("║"))}            ${bold(green("Local Setup Complete!"))}                ${bold(cyan("║"))}
${bold(cyan("╚══════════════════════════════════════════════════════╝"))}

${bold("Generated .env Files:")}
  ${green("✔")} apps/fleet-manager/.env
  ${green("✔")} apps/media-worker/.env

${bold("Next Steps:")}
  1. Queue & trigger a test transcoding job: ${cyan("pnpm fleet:queue:trigger")}
  2. Monitor fleet health & status:         ${cyan("pnpm fleet:cli status")}
`);

  return {
    success: true,
    provider: "local",
  };
}

/**
 * Full infrastructure setup workflow:
 * 1. Runs configureEnv()
 * 2. Prompts user to check .env files and confirm
 * 3. Runs provisionInfra()
 */
export async function runInfraSetup(
  options: ProviderInfraOptions = {},
): Promise<void> {
  const isNonInteractive =
    options.nonInteractive === true ||
    options.interactive === false ||
    process.env.CI === "true" ||
    process.argv.includes("--yes") ||
    process.argv.includes("-y") ||
    process.argv.includes("--non-interactive");

  if (!options.skipEnvConfig) {
    const configResult = await configureEnv(options);

    if (!isNonInteractive && process.stdin.isTTY) {
      console.log(`
${bold(cyan("--------------------------------------------------"))}
${bold(green("✔ Configuration saved!"))}
Please check envs on the paths:
${configResult.envFiles.map((f) => `  ${cyan("• " + path.relative(process.cwd(), f))}`).join("\n")}
You can change them if needed.
`);
      const rl = readline.createInterface({ input, output });
      const answer = (
        await rl.question(
          bold(
            yellow(
              "Proceed with infrastructure provisioning? (yes/no) [yes]: ",
            ),
          ),
        )
      )
        .trim()
        .toLowerCase();
      rl.close();

      if (answer && answer !== "yes" && answer !== "y") {
        console.log(yellow("Infrastructure provisioning cancelled by user."));
        return;
      }
    }
  }

  await provisionInfra(options);
}

export const runLocalInfraSetup = runInfraSetup;
export default runInfraSetup;

if (isMainModule(import.meta.url)) {
  runInfraSetup().catch((err: unknown) => {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`\n✘ Setup failed: ${msg}\n`);
    process.exit(1);
  });
}
